apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rp8v6bxly-dotnet-basic-gitops
  description: This is GitOps manifest for rp8v6bxly-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rp8v6bxly-dotnet-basic
    jenkins.io/job-full-name: rp8v6bxly-dotnet-basic-gitops
    backstage.io/kubernetes-id: rp8v6bxly-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rp8v6bxly-dotnet-basic
